Password_Generator/Password_Generator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('TPG/', include("TPG.urls"))
]

Password_Generator/TPG/urls.py
from django.urls import path
from . import views

app_name = "TPG"
urlpatterns = [
    path('', views.index, name="index"), 
    path('generate', views.generate, name='generate'),
    path('results', views.results, name='results')
]

Password_Generator/TPG/models.py
from django.db import models


    

Password_Generator/TPG/forms.py
from django import forms

class QuestionsForm(forms.Form):
    question1 = forms.CharField(max_length=100)
    question2 = forms.ChoiceField(choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3')])
    question3 = forms.IntegerField(min_value=10, max_value=99)

Password_Generator/TPG/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect
from TPG import algorithm 
import random 
import os

def index(request):
    return render(request, "index.html")

def generate(request):
    
    files = ['TPG/static/Questions1.txt','TPG/static/Questions2.txt','TPG/static/Questions3.txt']

    questions = []

    for file_name in files:
    #     Open the file and read all the questions
        with open(file_name, 'r') as f:
            all_questions = f.read().splitlines()
            
        selected_question = random.choice(all_questions)
        questions.append(selected_question)
        all_questions.clear()


    question1 = questions[0]
    question2 = questions[1]
    question3 = questions[2]

    return render(request, 'generate.html', {'question1': question1, 'question2': question2, 'question3': question3 })

def results(request):
    #this could b ethe could then return the password at the end

    # Process the form submission and generate the password
   
    answer1 = request.POST.get('answer1')
    answer2 = request.POST.get('answer2')
    answer3 = request.POST.get('answer3')
    answers = [[answer1],[answer2,'happy'],[answer3]]
    password = algorithm.generate_password(answers)

    # Save the password in the session
    request.session['password'] = password

    # Render the results template with the password
    return render(request, "results.html",{'password':password})

Password_Generator/TPG/templates/generate.html
{% extends "layout.html" %}

{% block body %}
<style>
  /* Show the first question by default */
  #question1 {
    display: block;
  }

  /* Hide all other questions by default */
  .question:not(#question1) {
    display: none;
  }
</style>
</head>
<body>
<form action="{% url 'TPG:results' %}" method="POST">
  {% csrf_token %}

  <!-- Question 1 -->
  <div class="question" id="question1">
    <h2>Question 1:</h2>
    <p>{{ question1 }}</p>
    <input type="text" name="answer1" required>
    <button type="button" onclick="showQuestion('question2', 'question1')">Next</button>
  </div>

  <!-- Question 2 -->
  <div class="question" id="question2">
    <h2>Question 2:</h2>
    <p>{{ question2 }}</p>
    <input type="text" name="answer2" required>
    <!-- <select name="answer2">
      {% for option in options %}
        <option value="{{ option }}">{{ option }}</option>
      {% endfor %}
    </select> -->
    <button type="button" onclick="showQuestion('question3', 'question2', 'question1')">Next</button>
    <button type="button" onclick="hideQuestion('question1')">Back</button>
  </div>

  <!-- Question 3 -->
  <div class="question" id="question3">
    <h2>Question 3:</h2>
    <p>{{ question3 }}</p>
    <input type="number" name="answer3" min="0" max="99">
    <button type="submit">Submit</button>
    <button type="button" onclick="hideQuestion('question2')">Back</button>
  </div>

</form>

<script>
  // Function to show a question
  function showQuestion(nextQuestionId, currentQuestionId, prevQuestionId) {
    // Hide the current question
    document.getElementById(currentQuestionId).style.display = "none";
    
    // Show the next question
    document.getElementById(nextQuestionId).style.display = "block";
    
    // Hide the previous question
    if (prevQuestionId) {
      document.getElementById(prevQuestionId).style.display = "none";
    }
  }

  // Function to hide a question
  function hideQuestion(questionId) {
    document.getElementById(questionId).style.display = "none";
  }
</script>


<!-- <form action="#" method="POST">
  {% csrf_token %}
  <h2>Question 1:</h2>
  <p>{{ question1 }}</p>
  <input type="text" name="answer1">

  <h2>Question 2:</h2>
  <p>{{ question2 }}</p>
  <input type="text" name="answer2">
  <select name="answer2">
    {% for option in options %}
      <option value="{{ option }}">{{ option }}</option>
    {% endfor %}
  </select>

  <h2>Question 3:</h2>
  <p>{{ question3 }}</p>
  <input type="number" name="answer3" min="0" max="99">

  <input type="submit" value="Submit">
</form> -->
{% endblock %}



Password_Generator/TPG/templates/index.html
{% extends "layout.html" %}

{% block body %}
<h1>This is the home page</h1>
{% endblock %}

Password_Generator/TPG/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>The Password Generator</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles.css'  %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="index.html"> <img src="{% static 'Logo2.png' %}" style="Height:60px"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav" >
            <a class="nav-link active " aria-current="page" href="{% url 'TPG:index' %}">Home</a>
            <a class="nav-link" href="{% url 'TPG:generate' %}">Create a Password</a>
            <a class="nav-link" href="#">Security Tips</a>
          </div>
        </div>
        <form class="d-flex" role="search">
        <button type="button" class="btn btn-outline-warning" onclick="openForm()">Recieve Breach Alerts</button>
      </form>
      </div>
    </nav>
    <div class="form-popup" id="myForm">
        <form action="/action_page.php" class="form-container">
          <h4>Get notified of any security breaches</h4>
          <input type="text" placeholder="Enter Email" name="email" required>
  
          <button type="submit" class="btn btn-outline-warning">Submit</button>
          <button type="button" class="btn cancel" onclick="closeForm()">Close</button>
        </form>
      </div>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
      <script type="text/javascript">
      function openForm() {
      document.getElementById("myForm").style.display = "block";
      }
  
      function closeForm() {
      document.getElementById("myForm").style.display = "none";
      }
      </script>
    {% block body %}
    {% endblock %}
  </body>
</html>

Password_Generator/TPG/templates/results.html
{% extends "layout.html" %}

{% block body %}
<h1>This is the results page, {{ password }}</h1>
{% endblock %}